name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: interfere
            asset_name: interfere-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: interfere.exe
            asset_name: interfere-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: interfere
            asset_name: interfere-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: interfere
            asset_name: interfere-macos-arm64
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }} --verbose
    
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
